global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'celery_flower'
    static_configs:
      - targets: ['flower:5556']

  - job_name: 'kafka_exporter'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'kafka_exporter:9308' ]

  - job_name: 'redis_exporter'
    static_configs:
      - targets: [ 'redis_exporter:9121' ]

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]
